version: "2"
services:
  geth:
    image: ethereum/client-go
    command: --datadir=/root/.ethereum/devchain --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 --http --http.addr=0.0.0.0 --http.api=personal,eth,net,web3 --http.corsdomain="*" --networkid=1234 --mine
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/keystore:/root/.ethereum/devchain/keystore:rw
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
  bootnode:
    image: ethereum/client-go
    command: bootnode --nodekeyhex="091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322" --verbosity=3
    ports:
      - "30301:30301/udp"
  netstats:
    image: sammyne/eth-netstats
    environment:
      - WS_SECRET=123
    ports:
      - "3000:3000"
